blank_issues_enabled: false
contact_links:
  - name: "GitHub Discussions"
    url: "https://github.com/orgs/r-a-tech-innovators/discussions"
    about: "Please ask and answer questions here."
    icon: "github"
